#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "anarchism"
name = "Anarchism"
description.en = "Exhaustive exploration of Anarchist theory and practice"
description.fr = "Exploration exhaustive de la théorie et de la pratique anarchiste"

version = "15.3-4~ynh1"

maintainers = ["kay0u"]

[upstream]
license = "GPL-2.0-or-later"
website = "https://salsa.debian.org/debian/anarchism/"
demo = "http://anarchism.pageabode.com/afaq/index.html"
admindoc = "https://salsa.debian.org/debian/anarchism"
code = "https://salsa.debian.org/debian/anarchism/"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/anarchism"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://salsa.debian.org/debian/anarchism/-/archive/debian/15.3-4/anarchism-debian-15.3-4.tar.bz2"
        sha256 = "20b80f407271e05af9c129d6c3cc969dc8fe687ac2427f48da2f058d86224760"
        autoupdate.strategy = "latest_gitlab_tag"
        autoupdate.version_regex = "^debian/(.*)$"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
