#!/bin/bash
app=anarchism

# Retrieve arguments
domain=$1
path=$2
is_public=$3

# Save app settings
sudo yunohost app setting $app is_public -v "$is_public"

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Install anarchism package
sudo apt-get install anarchism

# Modify Nginx configuration file and copy it to Nginx conf directory
final_path=/usr/share/doc/anarchism/html
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add url to SSOWat conf as skipped_uris
if [ "$is_public" = "Yes" ];
then
  # unprotected_uris allows SSO credentials to be passed anyway.
  sudo yunohost app setting $app unprotected_uris -v "/"
fi

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
